# Generated by Django 3.1.5 on 2021-02-20 23:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrewPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('postcode', models.CharField(max_length=20, verbose_name='Postcode')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('website', models.CharField(max_length=200, verbose_name='Website')),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
