# Generated by Django 3.1.5 on 2021-02-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewpoint',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='brewpoint',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='brewpoint',
            name='lon',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='brewpoint',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='brewpoint',
            name='postcode',
            field=models.CharField(max_length=20, null=True, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='brewpoint',
            name='street',
            field=models.CharField(max_length=100, null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='brewpoint',
            name='website',
            field=models.CharField(max_length=200, null=True, verbose_name='Website'),
        ),
    ]
